<main class="main-content" role="main">
<section id="usuario" class="section">
	<!-- .wrapper -->
	<div class="wrapper">
		<div class="row">
			<div class="col-md-12">
				<div class="col-md-3">
					<?php echo $this->partial('partials/menu_admin.phtml'); ?> 
				</div>
				<div class="col-md-9">
					<p><a href="/admin/categoria/cadastrar" class="btn btn-primary">Nova categoria</a></p>
					<h2>Categorias</h2>
					<p>Lorem ipsum</p>
					<br />
					<?php echo $this->flashMessenger()->render('error', array('alert', 'alert-danger')); ?>
				 	<?php echo $this->flashMessenger()->render('success', array('alert', 'alert-success')); ?>
				 	<?php echo $this->flashMessenger()->render('warning', array('alert', 'alert-warning')); ?>
					<table class="table table-striped table-bordered">
						<thead>
							<tr>
								<th></th>
								<th>Categoria</th>
								<th></th>
							</tr>
						</thead>
						<tbody>
							<?php foreach ($categorias as $categoria): ?>
							<tr>
								<td><a href="/admin/categoria/editar/<?php echo $categoria->id; ?>"><span
										title="Editar categoria" alt="Editar categoria"
										class="glyphicon glyphicon-pencil"></span></a></td>
							
								<td><?php echo $categoria->categoria; ?></td>
							
								<td><a onclick="return confirm('Confirma a remoção desta categoria?');" href="/admin/categoria/excluir/<?php echo $categoria->id; ?>"><span
										title="Excluir categoria" alt="Excluir categoria"
										class="glyphicon glyphicon-remove"></span></a></td>
							</tr>
							<?php endforeach; ?>
						</tbody>
					</table>
				</div>
			</div>
		</div>
	</div>
</section>
</main>