<?php echo $this->partial('partials/header_home.phtml'); ?>
<!-- .main-content -->
<main class="main-content" role="main"> <!-- .intro -->
<section id="intro" class="section intro">

	<header>
		<h1>Sistema de controle financeiro</h1>
		<hr />
		<p>Sistema de gestão de contas bancárias</p>
	</header>

	<a href="#funcionalidades" class="link animate">Conheça<span class="icon"></span></a> <a href="/portal/usuario/cadastrar">Cadastre-se<span></span></a>

</section>
<!-- end .intro --> <!-- .services -->
<section id="funcionalidades" class="section services">

	<!-- .wrapper -->
	<div class="wrapper">

		<h1>funcionalidades</h1>

		<!-- .row -->
		<div class="row">
			
			<div class="col-md-4 item web-design">
				<img src="images/icon_movimentation.png" alt="icon-web-design"
					width="82" height="82">
				<h2>Controle de movimentações bancárias</h2>
				<p>Cadastro de créditos e débitos categorizados</p>
			</div>

			<div class="col-md-4 item ui-design">
				<img src="images/icon_tag.png" alt="icon-ui-design" width="82"
					height="82">
				<h2>Controle de categorias</h2>
				<p>Semelhante a um plano de contas. O usuário pode cadastrar, editar e excluir os tipos de movimentações (categorias) e associá-las aos débitos e créditos.</p>
			</div>			

			<div class="col-md-4 item ecommerce">
				<img src="images/icon_dashboard.png" alt="icon-ecommerce" width="82"
					height="82">
				<h2>Dashboard</h2>
				<p>Painel com resumos dos créditos e débitos do mês corrente</p>
				<p></p>
			</div>

		</div>
		<!-- end .row -->

	</div>
	<!-- end .wrapper -->

</section>
<!-- end .services --> <!-- .work -->
<section id="quempodeusar" class="section work">

	<!-- .wrapper -->
	<div class="wrapper">

		<header>
			<h1>Quem pode usar</h1>
			<p class="intro-text">Este sistema serve apenas como modelo de desenvolvimento de aplicação web com a linguagem de programação PHP com auxílio do ORM Doctrine. Utiliza o Zend Framework 2 e o Bootstrap 2. Pode ser utilizado por profissionais ou estudantes da linguagem que desejam ter um sistema como base para o desenvolvimento de outros projetos.</p>
		</header>

		
</section>
<!-- end .work --> <!-- .about -->
<section id="quemsomos" class="about section">

	<!-- .wrapper -->
	<div class="wrapper">

		<header>
			<h1>Projeto</h1>
			<p class="intro-text">Projeto do Trabalho de Conclusão de Curso apresentado à disciplina de Metodologia da Pesquisa do Curso de Análise de Sistemas Orientados a Objetos do Centro Universitário IESB.</p>
		</header>

		<!-- .row -->
		<div class="row">
			

			<article class="col-md-12 col-sm-12 item">
				<header>
					<div class="img-wrapper">
						<img src="images/manoel.jpg"
							alt="Manoel Filho" width="150" height="150" />
					</div>
					<h2>Manoel Filho</h2>
					<p>Pós-graduando do curso de Análise de Sistemas Orientados a Objetos<br/>
do Centro Universitário IESB - Brasília/ DF
					</p>
				</header>
				<p>Orientador - Regiano da Silva Alves</p>
			</article>

			
		</div>
		<!-- end .row -->

	</div>
	<!-- end .wrapper -->

</section>
<!-- end .about --> <!-- .contact -->
