<?php echo $this->partial('partials/header_pages.phtml'); ?>
<main class="main-content" role="main">
<section id="usuario" class="section">
	<!-- .wrapper -->
	<div class="wrapper">
		<header>
			<h1>Cadastro</h1>
			<p>Preencha seus dados corretamente</p>
			<br/>
		</header>
		<div class="row">
			<div class="col-md-6">
				<div class="infocpf"></div>
				<div id="preloader">
					<p class="text-center">
						<img src="/images/financeiro/preloader.gif" alt="Carregando ..." title="Carregando ...">
					</p>
				</div>
				<br id="br">	 
	              <?php echo $this->flashMessenger()->render('error', array('alert', 'alert-danger')); ?>
				  <?php echo $this->flashMessenger()->render('success', array('alert', 'alert-success')); ?>						
				  <?php
						echo $this->form ()->openTag ( $form );
						echo $this->formCollection ( $form );
						echo $this->form ()->closeTag ();
				  ?>
			</div>
		</div>
	</div>
</section>
</main>