<?php echo $this->partial('partials/header_pages.phtml'); ?>
<?php $dominio = $_SERVER['SERVER_NAME']; ?>
<main class="main-content" role="main">
<section id="usuario" class="section">
	<!-- .wrapper -->
	<div class="wrapper">
		<header>
			<h1>Dados pessoais</h1>
		</header>
	        <?php echo $this->flashMessenger()->render('error', array('alert', 'alert-danger')); ?>
			<?php echo $this->flashMessenger()->render('success', array('alert', 'alert-success')); ?>
			<h3><?php echo $contato->nome; ?></h3><br/>
		<p>
			<span>Sexo:</span> <?php
			if ($contato->sexo == 'm') {
				echo 'Masculino';
			} else {
				echo 'Feminino';
			}
			?>
		</p>

		<p><span>Email: </span> <?php echo $contato->email; ?></p>
		<span>Categorias: </span>
		<ul>
			<?php foreach ($contato->getGrupos() as $grupo): ?>
				<li><?php echo $grupo->getGrupo(); ?></li>
			<?php endforeach; ?>
		</ul>
		<br/>
		<p>
			<a class="btn btn-primary" href="http://<?php echo $dominio; ?>/portal/usuario/editar">Editar dados pessoais</a> <a class="btn btn-success" href="http://<?php echo $dominio; ?>/admin">Minhas contas</a> <a class="btn btn-danger" href="http://<?php echo $dominio; ?>/portal/usuario/logout">Sair da minha conta</a>
		</p>
	</div>
</section>
</main>