<aside id="contato" class="section contact">

	<!-- .wrapper -->
	<div class="wrapper">

		<h1>Contato</h1>
		<p class="intro-text">
			Manoel Filho
		</p>

		<!-- .row -->
		<div class="row">	

			<div class="col-md-3 item email">
				<h2>Gmail:</h2>
				<p>
					<a href="mailto:manoel.tsf@gmail.com">manoel.tsf@gmail.com</a>
				</p>
			</div>

			<div class="col-md-3 item email">
				<h2>iCloud:</h2>
				<p>
					<a href="mailto:manoel.filho@icloud.com">manoel.filho@icloud.com</a>
				</p>
			</div>

			<div class="col-md-3 item skype">
				<h2>Skype:</h2>
				<p>manoel.tsf</p>
			</div>

			<div class="col-md-3 item social">
				<h2>Redes sociais:</h2>
				<p>
					<a href="http://facebook.com/manoel.tsf" class="facebook">Facebook</a>
				</p>
			</div>
		</div>
		<!-- end .row -->

	</div>
	<!-- end .wrapper -->

</aside>
<!-- end .contact --> </main>
<!-- end .main-content -->

<!-- .main-footer -->
<footer class="main-footer">
	<div class="wrapper">
		<p class="copyright">SISTEMA DE GESTÃO DE CONTAS BANCÁRIAS</p>
	</div>
</footer>
<!-- end .main-footer -->