<!-- .main-header -->
<header class="main-header">

	<!-- .wrapper -->
	<div class="wrapper">

		<nav class="navbar navbar-default" role="navigation">
			<div class="navbar-header">
				<button type="button" class="navbar-toggle" data-toggle="collapse"
					data-target=".navbar-collapse">
					<span class="sr-only">Toggle navigation</span> <span
						class="icon-bar"></span> <span class="icon-bar"></span> <span
						class="icon-bar"></span>
				</button>
				<h1 class="logo">
					<a href="http://<?php echo $_SERVER['SERVER_NAME']; ?>" title="Financeiro"><img
						src="/images/logo.png" alt="Financeiro" /></a>
				</h1>
			</div>
			<div class="collapse main-nav navbar-right navbar-collapse">
				<ul class="nav navbar-nav">
					
				</ul>
			</div>
		</nav>

	</div>
	<!-- end .wrapper -->

</header>
<!-- end .main-header -->