<!-- .main-header -->
<header class="main-header">

	<!-- .wrapper -->
	<div class="wrapper">

		<nav class="navbar navbar-default" role="navigation">
			<div class="navbar-header">
				<button type="button" class="navbar-toggle" data-toggle="collapse"
					data-target=".navbar-collapse">
					<span class="sr-only">Toggle navigation</span> <span
						class="icon-bar"></span> <span class="icon-bar"></span> <span
						class="icon-bar"></span>
				</button>
				<h1 class="logo">
					<a href="#intro" class="link animate" rel="home" title="Longfolio"><img
						src="images/logo.png" alt="Longfolio" /></a>
				</h1>
			</div>
			<div class="collapse main-nav navbar-right navbar-collapse">
				<ul class="nav navbar-nav">
					<li><a href="#funcionalidades" class="link animate">Funcionalidades</a></li>
					<li><a href="#quempodeusar" class="link animate">Quem pode usar</a></li>
					<li><a href="#quemsomos" class="link animate">Projeto</a></li>
					<li><a href="#contato" class="link animate">Contato</a></li>
					<li><a href="portal/usuario">Login</a></li>
				</ul>
			</div>
		</nav>

	</div>
	<!-- end .wrapper -->

</header>
<!-- end .main-header -->